### ISSUE TITLE
Fix: EditJobPage

### ISSUE THREAD

**Issue by Sandesh-Ghimire** [Sandesh-Ghimire/jobsite#3]
Edit page 404 not found.

**Comment by nirajgiriXD** [comment]
@Sandesh-Ghimire Could you please add description to clarify the issue? If possible, add screenshots as well.

**Comment by nirajgiriXD** [comment]
@Sandesh-Ghimire The should be fixed with this [PR](https://github.com/Sandesh-Ghimire/jobsite/pull/4).
